# Generated by Django 4.1.13 on 2024-01-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chatbotsteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotsteps',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
